name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            target: bundle-win
            pattern: dist/glyphx.exe
            artifact: glyphx-windows.exe
          - os: macos-latest
            target: bundle-mac
            pattern: dist/glyphx
            artifact: glyphx-macos
          - os: ubuntu-latest
            target: bundle-linux
            pattern: dist/glyphx
            artifact: glyphx-linux
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Extract version from tag
        id: version
        shell: bash
        run: |
          if [ "${{ github.ref_type }}" == "tag" ]; then
            VERSION="${{ github.ref_name }}"
            VERSION="${VERSION#v}"  # Remove 'v' prefix
          else
            VERSION="0.1.0-dev"
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Extracted version: $VERSION"
      
      - name: Update version in pyproject.toml
        shell: bash
        run: |
          VERSION="${{ steps.version.outputs.version }}"
          sed -i.bak "s/^version = .*/version = \"$VERSION\"/" pyproject.toml
          cat pyproject.toml | grep version
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]
      
      - name: Build bundle
        run: |
          make clean-bundles
          make ${{ matrix.target }}
      
      - name: Rename artifact
        shell: bash
        run: |
          cp "${{ matrix.pattern }}" "${{ matrix.artifact }}"
      
      - name: Upload to release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ matrix.artifact }}
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
